#Usamos node para construcción la build (npm run build)
FROM node:18-alpine as build

#Definimos el directorio de trabajo
WORKDIR /usr/src/app

#Copiamos dependencias
COPY package*.json ./

#instalamos dependencias
RUN npm ci 

#Copiamos el resto de archivos
COPY . .

# Recibir las variables como ARG y convertirlas en ENV
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_API_URL

ENV VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
ENV VITE_API_URL=${VITE_API_URL}

#Creamos el build para producción 
RUN npm run build 

#Usamos nginx para servir la app en producción
FROM nginx:alpine

#Copiamos los archivos estáticos de la etapa build 
COPY --from=build /usr/src/app/dist /usr/share/nginx/html 

#Copiamos configuracion de nginx 
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

#Exponemos el puerto 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]