describe ("Prueba de registro", () =>{
    it("Ingresar al login y registrarse como empresa", ()=>{
        cy.visit ('http://localhost:5173/')
        cy.get ('.button_signIn').first().click({force : true}).get('.goTo_register').click({force : true})
        cy.get('.container_AccountTypeEmpresa').click({force : true}).get('.form_register').first()
        cy.get('.form_register').first().find('input[type="email"]').first().type('alejandrosalascortez4@gmail.com')
        cy.get('.password-container').first().find('input[type="password"]').first().type('1234567890A$')
        cy.get('.confirmPassword-container').first().find('input[type="password"]').first().type('1234567890A$')
        cy.get('.button_register').first().click({force : true})
    })
    it ("Ingresar al login y registra", () =>{
         cy.visit ('http://localhost:5173/')
        cy.get ('.button_signIn').first().click({force : true}).get('.goTo_register').click({force : true})
        cy.get('.container_AccountTypeAprendiz').first().click({force : true}).get('.form_register').first()
        cy.get('.form_register').first().find('input[type="email"]').first().type('alejandro5@gmail.com')
        cy.get('.password-container').first().find('input[type="password"]').first().type('1234567890A$')
        cy.get('.confirmPassword-container').first().find('input[type="password"]').first().type('1234567890A$')
        cy.get('.button_register').first().click({force : true})
    })
    it ("Iniciar sesion administrador",() =>{
        cy.visit ('http://localhost:5173/')
        cy.get ('.button_signIn').first().click({force : true}).get('.content_createAccount')
        cy.get('.form_register').first().find('input[type="email"]').first().type('administrador@gmail.com')
        cy.get('.password-container').first().find('input[type="password"]').first().type('Admin1234*')
        cy.get('.button_register').click({force : true})
        cy.get('.container_options').get('.gestiones').first().click({force : true})
        cy.contains('button', 'Gestión de Instructores').first().click({force : true})
        cy.get('.btn_createInstructor').first().click({force : true})
        cy.get('.modal-left').contains('label', 'Nombres').find('input[type="text"]').type('eduard')
        cy.get('.modal-left').contains('label', 'Apellidos').find('input[type="text"]').type('cortez')
        cy.get('.modal-left').contains('label', 'Cédula').find('input[type="number"]').type('12345678901')
        cy.get('.modal-left').contains('label', 'Título').find('input[type="text"]').type('Instructor')
        cy.get('.modal-left').contains('label', 'Celular').find('input[type="number"]').type('30123456789')
        cy.get('.modal-left').contains('label', 'Email').find('input[type="email"]').type('vobebif221@fixwap.com')
        cy.get('.modal-right').get('.save-button').first().click({force : true})
    })
  
})